const LOGIN = 'App/LOGIN';
const LOGIN_SUCCESS = 'App/LOGIN_SUCCESS';

const FETCH_USER = 'App/FETCH_USER';
const FETCH_USER_SUCCESS = 'App/FETCH_USER_SUCCESS';

const REQUEST_FAILED = 'App/REQUEST_FAILED';

export default {
	LOGIN,
	LOGIN_SUCCESS,
	FETCH_USER,
	FETCH_USER_SUCCESS,
	REQUEST_FAILED,
};
