// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetCompositionByUserID(ctx context.Context, userID sql.NullInt64) ([]GetCompositionByUserIDRow, error)
	GetDiaryEntriesByUserID(ctx context.Context, userID sql.NullInt64) ([]GetDiaryEntriesByUserIDRow, error)
	GetExercisesByUserID(ctx context.Context, userID sql.NullInt64) ([]GetExercisesByUserIDRow, error)
	GetMealsByUserID(ctx context.Context, userID sql.NullInt64) ([]GetMealsByUserIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
}

var _ Querier = (*Queries)(nil)
