export const FETCH_BODY_COMP_REQUEST = "FETCH_BODY_COMP_REQUEST";
export const FETCH_BODY_COMP_SUCCESS = "FETCH_BODY_COMP_SUCCESS";
export const FETCH_BODY_COMP_FAILURE = "FETCH_BODY_COMP_FAILURE";
export const FETCH_MEALS_REQUEST = "FETCH_MEALS_REQUEST";
export const FETCH_MEALS_SUCCESS = "FETCH_MEALS_SUCCESS";
export const FETCH_MEALS_FAILURE = "FETCH_MEALS_FAILURE";
